const express=require('express'); const path=require('path'); const {Pool}=require('pg');
const app=express(); app.use(express.json({limit:'5mb'})); app.use(express.static(path.join(__dirname,'public')));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
async function init(){if(!pool)return; await pool.query(`CREATE TABLE IF NOT EXISTS contracts(id SERIAL PRIMARY KEY,cr TEXT UNIQUE NOT NULL,name TEXT NOT NULL,active BOOLEAN DEFAULT true); CREATE TABLE IF NOT EXISTS employees(id SERIAL PRIMARY KEY,registration TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT,contract_id INT REFERENCES contracts(id),role TEXT,shift TEXT,schedule TEXT,active BOOLEAN DEFAULT true); CREATE TABLE IF NOT EXISTS overtime(id SERIAL PRIMARY KEY,employee_id INT REFERENCES employees(id),work_date DATE NOT NULL,hours NUMERIC(6,2) DEFAULT 0); CREATE TABLE IF NOT EXISTS requests(id SERIAL PRIMARY KEY,employee_id INT REFERENCES employees(id),type TEXT NOT NULL,reference TEXT,message TEXT,status TEXT DEFAULT 'Pendente',created_at TIMESTAMPTZ DEFAULT now());`)}
app.get('/api/health',(q,s)=>s.json({ok:true,app:'OPERA IA'}));
app.get('/api/dashboard',async(q,s)=>{if(!pool)return s.json({demo:true,contracts:0,employees:0,overtime:0,pending:0}); try{let r=await pool.query(`SELECT (SELECT count(*) FROM contracts WHERE active)::int contracts,(SELECT count(*) FROM employees WHERE active)::int employees,(SELECT coalesce(sum(hours),0) FROM overtime WHERE date_trunc('month',work_date)=date_trunc('month',current_date)) overtime,(SELECT count(*) FROM requests WHERE status='Pendente')::int pending`);s.json(r.rows[0])}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/contracts',async(q,s)=>{if(!pool)return s.status(503).json({error:'Banco não configurado'});let {cr,name}=q.body; try{let r=await pool.query('INSERT INTO contracts(cr,name) VALUES($1,$2) ON CONFLICT(cr) DO UPDATE SET name=excluded.name RETURNING *',[cr,name]);s.json(r.rows[0])}catch(e){s.status(400).json({error:e.message})}});
app.post('/api/employees',async(q,s)=>{if(!pool)return s.status(503).json({error:'Banco não configurado'});let {registration,name,phone,cr,role,shift,schedule}=q.body;try{let c=await pool.query('SELECT id FROM contracts WHERE cr=$1',[cr]);if(!c.rowCount)return s.status(400).json({error:'CR não cadastrado'});let r=await pool.query(`INSERT INTO employees(registration,name,phone,contract_id,role,shift,schedule) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(registration) DO UPDATE SET name=excluded.name,phone=excluded.phone,contract_id=excluded.contract_id,role=excluded.role,shift=excluded.shift,schedule=excluded.schedule RETURNING *`,[registration,name,phone,c.rows[0].id,role,shift,schedule]);s.json(r.rows[0])}catch(e){s.status(400).json({error:e.message})}});
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html'))); const port=process.env.PORT||3000; init().then(()=>app.listen(port,()=>console.log('OPERA IA :'+port))).catch(e=>{console.error(e);app.listen(port)});
